# Generated by Django 5.0.2 on 2025-10-08 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_festival', '0010_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_festival.event')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_festival.film')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'film')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='proposed_films',
            field=models.ManyToManyField(related_name='events', through='film_festival.EventFilm', to='film_festival.film'),
        ),
    ]
