# Generated by Django 5.0.2 on 2025-10-08 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_festival', '0011_eventfilm_event_proposed_films'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfilm',
            name='upvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EventFilmUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='film_festival.eventfilm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event_film', 'user')},
            },
        ),
    ]
