# Generated by Django 5.0.2 on 2025-09-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='study',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='technicalskill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.DeleteModel(
            name='TechnicalSkillCategory',
        ),
        migrations.DeleteModel(
            name='TechnicalSkill',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
