name: Deploy to my server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to my server
      run: |
        ssh -o StrictHostKeyChecking=no iamoros@api.ivanamoros.com -p 2222 << 'EOF'
        cd /home/iamoros/back_port/
        git pull origin master
        source /home/iamoros/env/bin/activate
        pip install -r requirements.txt
        python3 manage.py migrate
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx
        EOF
